spring:
  mail:
    properties:
      mail:
        smtp:
          socketFactory:
            port: '465'
            class: javax.net.ssl.SSLSocketFactory
            fallback: 'false'
          starttls:
            enable: 'true'
          auth: 'true'
      support:
        email: xyz@gmail.com
    username: lositha.production@gmail.com
    default-encoding: UTF-8
    host: smtp.gmail.com
    test-connection: 'false'
    password: psEJ5Zl11rE5
  main:
    allow-bean-definition-overriding: 'true'
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: 'true'
  cache:
    jcache:
      config: classpath:ehcache3.xml
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    password: pera-pgis-20
    username: covid_user@covid19-db-sever
    url: jdbc:mysql://covid19-db-sever.mysql.database.azure.com:3306/covid19data?useSSL=true&requireSSL=false
  jackson:
    serialization:
      fail-on-empty-beans: 'false'

info:
  app:
    name: Covid19 Contact Tracer
    version: 1.0.0
    description: PGIS - UOP

twilio:
  PHONE_NUMBER: '+12184025616'
  ACCOUNT_SID: ACb06aa4fbc924c253c831fab488bd1ac9
  AUTH_TOKEN: 610e356f95a6e2e530f4054e20bf99d5

server:
  servlet:
    session:
      timeout: 20m
