server:
  port: '8080'
  servlet:
    session:
      timeout: 20m
spring:
  datasource:
    url: >-
      jdbc:mysql://contact-tracer-db-server.mysql.database.azure.com:3306/contact-tracer-db-server?useSSL
    username: contacttracerudb@contact-tracer-db-server
    password: contact-tracer-u-db-2020
    hikari:
      connection-timeout: '20000'
      minimum-idle: '15'
      maximum-pool-size: '25'
      idle-timeout: '300000'
      max-lifetime: '1200000'
      auto-commit: 'true'
      data-source-properties:
        createDatabaseIfNotExist: 'true'
        useUnicode: 'true'
        characterEncoding: UTF-8
        autoReconnect: 'true'
        useSSL: 'true'
        maxAllowedPacket: '1073741824'
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        connection:
          characterEncoding: utf-8
          CharSet: UFT-8
          useUnicode: 'true'
          autoReconnect: 'true'
          useSSL: 'true'
    open-in-view: 'true'
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    serialization:
      fail-on-empty-beans: 'false'
  main:
    allow-bean-definition-overriding: 'true'
  mail:
    host: smtp.gmail.com
    username: lositha.production@gmail.com
    password: psEJ5Zl11rE5
    properties:
      mail:
        smtp:
          auth: 'true'
          starttls:
            enable: 'true'
          socketFactory:
            port: '465'
            class: javax.net.ssl.SSLSocketFactory
            fallback: 'false'
      support:
        email: xyz@gmail.com
    default-encoding: UTF-8
    test-connection: 'false'
  cache:
    jcache:
      config: 'classpath:ehcache3.xml'
info:
  app:
    name: Covid19 Contact Tracer
    description: PGIS - UOP
    version: 1.0.0
management:
  health:
    defaults:
      enabled: 'false'
logging:
  config: 'classpath:log_config.xml'
twilio:
  ACCOUNT_SID: ACb06aa4fbc924c253c831fab488bd1ac9
  AUTH_TOKEN: 610e356f95a6e2e530f4054e20bf99d5
  PHONE_NUMBER: '+12184025616'
